TITLES = {
 'greater-accra|Jamestown':'Jamestown/Usshertown, Accra',
 'greater-accra|Kwame Nkrumah Memorial Park':'Kwame Nkrumah Memorial Park',
 'greater-accra|Makola Market':'Makola, Ghana',
 'greater-accra|Labadi Beach':'Labadi Beach',
 'greater-accra|Osu':'Osu, Accra',
 'greater-accra|Arts Centre for National Culture':'National Cultural Centre',
 'central|Cape Coast Castle':'Cape Coast Castle',
 'central|Kakum National Park':'Kakum National Park',
 'central|Elmina Castle':'Elmina Castle',
 'central|Assin Manso Ancestral Slave River':'Assin Manso Slave River Site',
 'central|Hans Cottage Botel':None,
 'volta|Wli Falls':'Wli waterfalls',
 'volta|Mount Afadja':'Mount Afadja',
 'volta|Tafi Atome Monkey Sanctuary':'Tafi Atome Monkey Sanctuary',
 'volta|Amedzofe':'Amedzofe, Ghana',
 'volta|Keta Lagoon':'Keta Lagoon',
 'savannah|Mole National Park':'Mole National Park',
 'savannah|Larabanga Mosque':'Larabanga Mosque',
 'savannah|Mognori Eco Village':None,
 'savannah|Salaga':'Salaga',
 'western|Nzulezu':'Nzulezu',
 'western|Busua Beach':'Busua',
 'western|Cape Three Points':'Cape Three Points',
 'western|Fort San Antonio, Axim':'Fort San Antonio',
 'western|Ankasa Conservation Area':'Ankasa Conservation Area',
 'ashanti|Manhyia Palace Museum':'Manhyia Palace',
 'ashanti|Kejetia Market':'Kejetia Market',
 'ashanti|The Great Hall, KNUST':'Kwame Nkrumah University of Science and Technology',
 'ashanti|Lake Bosomtwe':'Lake Bosomtwe',
 'ashanti|Bonwire':'Bonwire',
 'ashanti|Ntonso':'Ntonso',
 'eastern|Aburi Botanical Gardens':'Aburi Botanical Gardens',
 'eastern|Akosombo Dam':'Akosombo Dam',
 'eastern|Boti Falls':'Boti Falls',
 'eastern|Umbrella Rock':'Umbrella Rock (Ghana)',
 'eastern|Bunso Arboretum':'Bunso Arboretum',
 'northern|Central Mosque, Tamale':'Tamale Central Mosque',
 'northern|Tamale Central Market':'Tamale',
 'northern|Gbewaa Palace, Yendi':'Gbewaa Palace',
 'northern|Daboya':'Daboya',
 'upper-east|Paga Crocodile Pond':'Paga Crocodile Pond',
 'upper-east|Bolgatanga Market':'Bolgatanga',
 'upper-east|Sirigu':'Sirigu',
 'upper-east|Tongo Hills and Tengzug':'Tongo Hills',
 'upper-east|Navrongo Cathedral':'Our Lady of Seven Sorrows Cathedral, Navrongo',
 'upper-west|Wa Naa\'s Palace':'Wa Naa\'s Palace',
 'upper-west|Wechiau Community Hippo Sanctuary':'Wechiau Community Hippo Sanctuary',
 'upper-west|Gwollu Defence Wall':'Gwollu',
 'upper-west|Nandom':'Nandom',
 'north-east|Nalerigu':'Nalerigu',
 'north-east|Naa Jaringa Wall, Gambaga':'Gambaga',
 'north-east|Gambaga Escarpment':'Gambaga Escarpment',
 'north-east|Nakpanduri':'Nakpanduri',
 'oti|Lake Volta at Dambai':'Dambai',
 'oti|Kyabobo National Park':'Kyabobo National Park',
 'oti|Nkwanta':'Nkwanta',
 'bono|Boabeng-Fiema Monkey Sanctuary':'Boabeng-Fiema Monkey Sanctuary',
 'bono|Sunyani':'Sunyani',
 'bono|Bui National Park':'Bui National Park',
 'bono-east|Kintampo Waterfalls':'Kintampo waterfalls',
 'bono-east|Techiman Market':'Techiman',
 'bono-east|Fuller Falls':'Fuller Falls',
 'bono-east|Buoyem Caves':'Buoyem',
 'ahafo|Goaso':'Goaso',
 'ahafo|Mim':'Mim, Ghana',
 'ahafo|Kenyasi':'Kenyasi',
 'western-north|Bia National Park':'Bia National Park',
 'western-north|Sefwi Wiawso':'Sefwi Wiawso',
 'western-north|Cocoa country':None,
}
